name: "CI"
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mfinelli/setup-shfmt@v3
      - uses: open-turo/action-pre-commit@v3

  # no tests as of now but expected by branch protection rules
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: echo noop
